# -*- coding: utf-8 -*-
"""2_Data_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0HArNpOIWLyjUepxJQxoxeJMde8CAlR
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# Project: Arabic Abstracts Analysis (Human vs AI)
# Author: Hassan Hashem
# ============================================================
#Establish the link between Colab and github repositary
!git clone https://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@github.com/hhashem4/arabic-abstracts-analysis.git
# %cd arabic-abstracts-analysis
# =======================
# Setup
# =======================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =======================
# Load Dataset from the CSV file
# =======================

# Load CSV directly from GitHub raw link
url = "https://raw.githubusercontent.com/hhashem4/arabic-abstracts-analysis/main/data/by_polishing.csv"
df_polish = pd.read_csv(url)

# Display first rows
print(df_polish.head())

# =======================
# Initial Exploration
# =======================

# 1. Shape of data
print("\nDataset Shapes:")
print("by_polishing:", df_polish.shape)

# 2. Check for missing values
print("\nMissing values (by_polishing):")
print(df_polish.isnull().sum())

# 3. Check for duplicates
print("\nDuplicates (by_polishing):", df_polish.duplicated().sum())

# =======================
# Example: Construct Labels
# =======================
# If no explicit "label" column exists:
# Let's define a simple label scheme:
#   - 0 = Human-written abstract
#   - 1 = AI-generated abstract

df_polish_human = df_polish[["original_abstract"]].copy()
df_polish_human["label"] = 0

df_polish_ai = df_polish[["allam_generated_abstract"]].copy()
df_polish_ai = df_polish_ai.rename(columns={"allam_generated_abstract": "original_abstract"})
df_polish_ai["label"] = 1

df_combined = pd.concat([df_polish_human, df_polish_ai], ignore_index=True)

print("\nCombined dataset shape:", df_combined.shape)
print(df_combined["label"].value_counts())

# =======================
# Data Visualization
# =======================

# Distribution of abstract lengths (human vs AI)
df_combined["length"] = df_combined["original_abstract"].str.split().apply(len)

plt.figure(figsize=(8,5))
sns.histplot(data=df_combined, x="length", hue="label", bins=50, kde=True)
plt.title("Distribution of Abstract Lengths: Human vs AI")
plt.xlabel("Word Count")
plt.ylabel("Frequency")
plt.legend(["Human (0)", "AI (1)"])
# Save figure as JPG
plt.savefig("histogram.jpg", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("histogram.jpg")  # or "histogram.jpg"

